version: '2'
services:
    questmio-app:
        image: questmio
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://questmio-mysql:3306/questmio?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    questmio-mysql:
        extends:
            file: mysql.yml
            service: questmio-mysql
